name: Build and Publish Docker Image

# Publish Docker image on pushes to main branch, or on-demand.
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get/Set Tag Info
        id: tag-info
        run: ./scripts/write-tag-info.sh && ./scripts/set-github-env.sh
      - name: Print Tag Info
        run: echo "Will build docker image for ${{ steps.tag-info.outputs.IMAGE_TAG_LATEST }} and ${{ steps.tag-info.outputs.IMAGE_TAG_TIMESTAMP }}"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build, Tag, and Publish Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ steps.tag-info.outputs.IMAGE_TAG_LATEST }},${{ steps.tag-info.outputs.IMAGE_TAG_TIMESTAMP }}
          push: true